services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: restaurant_user_db
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3308:3306"
    volumes:
      - "./db/schema:/docker-entrypoint-initdb.d"
      - "db-volume:/var/lib/mysql"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: projeto-integrador-3-app
    volumes:
      - "./:/var/www/html"
    ports:
      - 81:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
volumes:
  db-volume:
